config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, :text, presence: true

  broadcasts_to -> (note) { "notes" }, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :find_note, only: %i[destroy edit update]
  def index
    @notes = Note.order(created_at: :desc)
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Note was successfully created!" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @note.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Note was successfully deleted!" }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @note.update(note_params)
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Note was successfully edited!" }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :text)
  end

  def find_note
    @note = Note.find(params.require(:id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notepad RoR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-gray-50 min-h-screen">
    <%= yield %>
  </body>
</html>

app/views/notes/_button_partial.html.erb
<%= turbo_frame_tag "new_note" do %>
  <div class="text-center mb-4">
    <%= link_to "New note", new_note_path, class: "inline-block bg-indigo-500 text-white p-2 rounded-md hover:bg-indigo-600" %>
  </div>
<% end %>

app/views/notes/_form.html.erb
<div class="container mx-auto p-4">
  <%= form_with model: note, class: "space-y-6" do |form| %>

    <% if note.errors.any? %>
      <div class="bg-red-100 text-red-700 p-4 rounded-md mb-4 border border-red-300">
        <%= note.errors.full_messages.to_sentence.capitalize %>
      </div>
    <% end %>

    <div class="space-y-4">
      <div>
        <%= form.label :title, "Título", class: "block text-gray-700 font-bold text-lg mb-2" %>
        <%= form.text_field :title, class: "w-1/3 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" %>
      </div>

      <div>
        <%= form.label :text, "Texto", class: "block text-gray-700 font-bold text-lg mb-2" %>
        <%= form.text_area :text, size: "70x5", class: "w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" %>
      </div>
    </div>

    <div class="flex justify-between items-center mb-4">
      <%= link_to "Cancelar", notes_path, class: "bg-gray-200 text-gray-800 py-2 px-4 rounded-md hover:bg-gray-300" %>
      <%= form.submit "Salvar", class: "bg-indigo-500 text-white py-3 px-6 rounded-md hover:bg-indigo-600" %>
    </div>
  <% end %>
</div>

app/views/notes/_note.html.erb
<%= turbo_frame_tag note do %>
  <div class="container mx-auto p-4">
    <div class="bg-gray-100 shadow-md rounded-lg p-6 mb-4">
      <h2 class="text-3xl font-bold text-gray-800 mb-4 border-b-2 border-gray-300 pb-2 inline-block"><%= note.title %></h2>
      <p class="text-gray-600 text-lg"><%= note.text %></p>
    </div>

    <div class="flex space-x-2">
      <%= button_to "Delete", note_path(note), method: :delete, class: "bg-red-600 text-white py-2 px-4 rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50" %>
      <%= link_to "Edit", edit_note_path(note), class: "bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
    </div>
  </div>
<% end %>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.prepend "notes" do %>
  <% render @note %>
<% end %>

<%= turbo_stream.replace "new_note", partial: "button_partial" %>

<%= turbo_stream.update "message", inline: '<div class="bg-green-100 text-green-700 p-4 rounded-md mb-4 border border-green-300"><p>Note was successfully created</p></div>' %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove @note %>

<%= turbo_stream.update "message", inline: '<div class="bg-red-100 text-red-700 p-4 rounded-md mb-4 border border-red-300"><p>Note was successfully deleted</p></div>' %>

app/views/notes/edit.html.erb
<%= turbo_frame_tag dom_id(@note) do %>
  <%= render "form", note: @note %>
<% end %>

app/views/notes/index.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-center text-3xl font-bold mb-6">Notepad RoR</h1>

  <%= turbo_frame_tag "new_note" do %>
    <div class="text-center mb-4">
      <%= link_to "+ New Note", new_note_path, class: "inline-block bg-green-500 text-white py-2 px-4 rounded-md hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50" %>
    </div>
  <% end %>

  <%= turbo_frame_tag "message" do %><% end %>

  <%= turbo_frame_tag "notes" do %>
    <%= render @notes %>
  <% end %>
</div>

<%= turbo_stream_from "notes" %>

app/views/notes/new.html.erb

<%= turbo_frame_tag "new_note" do %>
  <%= render "form", note: @note %>
<% end %>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@note), partial: "note", locals: { note: @note} %>